name: Example
on:
   push:
      branches:
      - main
      - task*
   pull_request:
      types: [opened, synchronize, reopened]

jobs:
  uv-install:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install requirements
        run: uv sync --locked
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Build and push Docker image
        run: |
          docker build -t my-image:latest .
          docker tag my-image:latest my-registry/my-image:latest